{% set version=load_setup_py_data().get('version') %}

package:
  name: oncoviruses
  version: "{{ version }}"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python ==3.7.*
    - versionpy
    - ngs_utils >=2.7.0
  run:
    - python ==3.7.*
    - ngs_utils
    - click
    - snakemake
    - samtools
    - sambamba
    - mosdepth
    - bwa
    - bcftools
    - ngs_utils >=2.7.0

test:
  commands:
    - oncoviruses --help

about:
  home: https://github.com/umccr/oncoviruses
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  summary: "'Detection of oncoviruses in tumor whole genome samples'"
