#!/usr/bin/env python
import sys
import os
from os.path import dirname, abspath, join, basename, isfile, isdir, splitext
import click
from hpc_utils import hpc
from ngs_utils.call_process import run_simple
from ngs_utils.file_utils import which, safe_mkdir, splitext_plus, verify_dir, file_exists, verify_file
from ngs_utils import logger as log
from ngs_utils.snakemake_utils import run_snakemake
from ngs_utils.utils import set_locale; set_locale()
from oncoviruses import package_path


@click.command()
@click.argument('bam', type=click.Path(exists=True))
@click.option('-o', '--output-dir', 'output_dir', type=click.Path())
# Reference: either --viruses-fa and (--host-fa or --combined-reference) explicitly, or --genomes and optional -g
@click.option('--host-fa', 'host_fa', help='Path to host reference (e.g. hg38.fa)')
@click.option('--viruses-fa', 'viruses_fa',
              help='Path to viral sequences bwa index prefix (e.g. gdc-viral.fa from bcbio bundle)')
@click.option('--combined-fa', 'combined_fa',
              help='To speed up the analysis, you can merge the host and viral fasta '
                   'and index with `samtools faidx` and `bwa index`')
@click.option('--genomes', '--genomes-dir', 'genomes_dir',
              help='Path to umccrise genomes, alternative to all "*-fa" options')

@click.option('-s', '--sample-name' '--prefix', 'sample_name',
              help='Prefix for output files. Default is the basename of the output file.')
@click.option('-v', '--virus', 'virus',
              help='Optional virus species to check for (e.g. hpv16, hpv33, etc.). '
                   'If not provided, will be detected.')

@click.option('-t', '--threads', '-j', '--jobs', '--cores', 'requested_cores', type=click.INT,
              help='Maximum number of cores to use at single time (works both for local and cluster runs)')
@click.option('--unlock', 'unlock', is_flag=True)
@click.option('-n', '--dryrun', 'dryrun', is_flag=True,
              help='Propagated to snakemake. Prints rules and commands to be run without actually executing them.')

def main(bam, output_dir, host_fa, viruses_fa, combined_fa, genomes_dir=None, sample_name=None, virus=None,
         requested_cores=None, dryrun=None, unlock=None):

    if not bam.endswith('.bam'):
        raise click.BadParameter(f'Input must be a BAM file, got: {bam}')
    if not sample_name:
        sample_name = splitext(basename(bam))[0]

    output_dir = output_dir or 'oncoviruses'
    output_dir = safe_mkdir(abspath(output_dir))
    log_dir = safe_mkdir(join(output_dir, 'log'))
    log.init(log_fpath_=join(log_dir, 'command.txt'), save_previous=True)

    if isfile(join(output_dir, 'work', 'all.done')):
        run_simple('rm ' + join(output_dir, 'work', 'all.done'))

    try:
        cores = len(os.sched_getaffinity(0))
    except:
        cores = 1
    if requested_cores:
        cores = min(requested_cores, cores)
    conf = {
        'input_bam': abspath(bam),
        'output_dir': abspath(output_dir),
        'sample_name': sample_name,
        'cores': cores,
    }

    if virus:
        conf['virus'] = virus

    # check hpc_utils can find the genomes dir, and error out if not
    hpc.set_genomes_dir(genomes_dir)
    if hpc.genomes_dir:
        conf['genomes_dir'] = hpc.genomes_dir
    if combined_fa:
        if not verify_file(combined_fa + '.bwt'):
            log.critical(f'Please, index {combined_fa} with `bwa index {combined_fa}`')
        conf['combined_fa'] = combined_fa
    if viruses_fa:
        if not verify_file(viruses_fa + '.bwt'):
            log.critical(f'Please, index {viruses_fa} with `bwa index {viruses_fa}`')
        if not verify_file(viruses_fa + '.fai'):
            log.critical(f'Please, index {viruses_fa} with `samtools faidx {viruses_fa}`')
        conf['viruses_fa'] = verify_file(viruses_fa)
    if not hpc.genomes_dir:
        if not viruses_fa:
            log.critical(f'Please provide either --combined-fa, or both --host-fa and --viruses-fa, or --genomes-dir')
        if not viruses_fa or (not combined_fa and not host_fa):
            log.critical(f'Please provide either --viruses-fa and (--combined-fa or --host-fa), or --genomes-dir')
        if host_fa:
            conf['host_fa'] = verify_file(host_fa)

    # Checking that configManta.py and python2 is available, or if running in umccrise envirnoment so _python2 env is there
    py2_env_path = hpc.secondary_conda_env('python2')
    conf['py2_env_path'] = py2_env_path

    run_snakemake(join(package_path(), "workflow.smk"), conf, output_dir=output_dir,
                  jobs=cores, unlock=unlock, dryrun=dryrun)

    result_path = join(output_dir, 'breakpoints.vcf.gz')
    prio_tsv = join(output_dir, 'prioritized_oncoviruses.tsv')
    if not verify_file(result_path, silent=True):
        log.warn(
            f'Not found any viruses with significant coverage. '
            f'You can explore the full list at {prio_tsv} and rerun with '
            f'the --virus option explicitly.')
    else:
        log.info(f'Breakpoints reported in {result_path}, '
                 f'prioritized viruses reported in {prio_tsv}')


if __name__ == '__main__':
    main()






